
export const GALLERY = 'GALLERY';
export const GALLERY_PENDING = 'GALLERY_PENDING';
export const GALLERY_FULFILLED = 'GALLERY_FULFILLED';
export const GALLERY_REJECTED = 'GALLERY_REJECTED';

export const IMAGE = 'IMAGE';
export const IMAGE_PENDING = 'IMAGE_PENDING';
export const IMAGE_FULFILLED = 'IMAGE_FULFILLED';
export const IMAGE_REJECTED = 'IMAGE_REJECTED';

export const FILTER_CHANGED = 'FILTER_CHANGED';